/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '1rem',
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
      },
    },
    extend: {
      colors: {
        // Anthropic Claude Official Colors
        claude: {
          orange: '#d97757',
          'orange-hover': '#c56644',
          'orange-light': '#DE7356',
          blue: '#6a9bcc',
          'blue-hover': '#5a8bbc',
          green: '#788c5d',
          'green-hover': '#687c4d',
          dark: '#141413',
          light: '#faf9f5',
          'mid-gray': '#b0aea5',
          'light-gray': '#e8e6dc',
          // Product UI tokens
          'bg-primary': '#1a1918',
          'bg-secondary': '#242320',
          'bg-tertiary': '#2e2d2a',
          'bg-elevated': '#353432',
        },
        // Semantic mappings using Claude theme
        border: 'rgba(176, 174, 165, 0.2)',
        input: '#2e2d2a',
        ring: '#d97757',
        background: '#141413',
        foreground: '#faf9f5',
        canvas: '#141413',
        surface: '#1a1918',
        'surface-elevated': '#242320',
        'surface-active': '#353432',
        terminal: '#1a1918',
        'border-subtle': 'rgba(176, 174, 165, 0.15)',
        'border-default': 'rgba(176, 174, 165, 0.25)',
        'border-focus': '#d97757',
        'border-active': '#d97757',
        primary: {
          DEFAULT: '#d97757',
          hover: '#c56644',
          text: '#faf9f5',
          foreground: '#faf9f5',
        },
        secondary: {
          DEFAULT: '#6a9bcc',
          hover: '#5a8bbc',
          foreground: '#faf9f5',
        },
        accent: {
          DEFAULT: '#788c5d',
          hover: '#687c4d',
          foreground: '#faf9f5',
        },
        'text-primary': '#faf9f5',
        'text-secondary': '#b0aea5',
        'text-tertiary': 'rgba(176, 174, 165, 0.6)',
        success: '#788c5d',
        warning: '#d97757',
        danger: '#d4183d',
        info: '#6a9bcc',
        destructive: {
          DEFAULT: '#d4183d',
          foreground: '#faf9f5',
        },
        muted: {
          DEFAULT: '#2e2d2a',
          foreground: '#b0aea5',
        },
        popover: {
          DEFAULT: '#242320',
          foreground: '#faf9f5',
        },
        card: {
          DEFAULT: '#1a1918',
          foreground: '#faf9f5',
        },
        // Legacy iOS colors for compatibility
        ios: {
          blue: '#6a9bcc',
          green: '#788c5d',
          orange: '#d97757',
          red: '#d4183d',
          gray: {
            1: '#b0aea5',
            2: '#9a9890',
            3: '#84827a',
            4: '#6e6c64',
            5: '#58564e',
            6: '#424038',
          },
          separator: 'rgba(176, 174, 165, 0.2)',
        },
      },
      fontFamily: {
        // Claude Typography - System fonts with good fallbacks
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
        display: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        heading: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        // Typography Scale
        'xs': ['11px', { lineHeight: '14px' }],
        'sm': ['13px', { lineHeight: '18px' }],
        'base': ['15px', { lineHeight: '22px' }],
        'lg': ['17px', { lineHeight: '24px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
        // Mobile-optimized scale
        'ios-caption2': ['11px', { lineHeight: '13px', letterSpacing: '0.07px' }],
        'ios-caption1': ['12px', { lineHeight: '16px' }],
        'ios-footnote': ['13px', { lineHeight: '18px', letterSpacing: '-0.08px' }],
        'ios-subhead': ['15px', { lineHeight: '20px', letterSpacing: '-0.24px' }],
        'ios-callout': ['16px', { lineHeight: '21px', letterSpacing: '-0.32px' }],
        'ios-body': ['17px', { lineHeight: '22px', letterSpacing: '-0.41px' }],
        'ios-headline': ['17px', { lineHeight: '22px', letterSpacing: '-0.41px', fontWeight: '600' }],
        'ios-title3': ['20px', { lineHeight: '25px', letterSpacing: '0.38px' }],
        'ios-title2': ['22px', { lineHeight: '28px', letterSpacing: '0.35px' }],
        'ios-title1': ['28px', { lineHeight: '34px', letterSpacing: '0.36px' }],
        'ios-large-title': ['34px', { lineHeight: '41px', letterSpacing: '0.37px' }],
      },
      spacing: {
        'ios-xs': '4px',
        'ios-sm': '8px',
        'ios-md': '12px',
        'ios-lg': '16px',
        'ios-xl': '20px',
        'ios-2xl': '24px',
        'touch': '44px',
        'touch-lg': '48px',
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      borderRadius: {
        'ios-sm': '8px',
        'ios-md': '12px',
        'ios-lg': '16px',
        'ios-xl': '20px',
        'ios-2xl': '24px',
        'ios-full': '9999px',
        'claude': '10px',
      },
      boxShadow: {
        'ios-sm': '0 1px 3px rgba(0, 0, 0, 0.2)',
        'ios-md': '0 4px 6px rgba(0, 0, 0, 0.25)',
        'ios-lg': '0 10px 20px rgba(0, 0, 0, 0.3)',
        'ios-sheet': '0 -4px 20px rgba(0, 0, 0, 0.35)',
        'ios-card': '0 2px 10px rgba(0, 0, 0, 0.2)',
        'claude': '0 2px 8px rgba(0, 0, 0, 0.15)',
        'claude-lg': '0 8px 24px rgba(0, 0, 0, 0.25)',
      },
      animation: {
        'ios-bounce': 'ios-bounce 0.3s ease-out',
        'ios-slide-up': 'ios-slide-up 0.35s cubic-bezier(0.32, 0.72, 0, 1)',
        'ios-slide-down': 'ios-slide-down 0.35s cubic-bezier(0.32, 0.72, 0, 1)',
        'ios-fade-in': 'ios-fade-in 0.2s ease-out',
        'ios-scale': 'ios-scale 0.2s ease-out',
        'pulse-subtle': 'pulse-subtle 2s ease-in-out infinite',
        'spin-slow': 'spin 2s linear infinite',
      },
      keyframes: {
        'ios-bounce': {
          '0%': { transform: 'scale(0.95)' },
          '50%': { transform: 'scale(1.02)' },
          '100%': { transform: 'scale(1)' },
        },
        'ios-slide-up': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'ios-slide-down': {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(100%)', opacity: '0' },
        },
        'ios-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'ios-scale': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      backdropBlur: {
        'ios': '20px',
        'ios-heavy': '40px',
      },
      transitionTimingFunction: {
        'ios': 'cubic-bezier(0.32, 0.72, 0, 1)',
        'ios-spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}