// Script Generator - Generate Claude setup scripts
Deno.serve(async (req) => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
  };

  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const { agentConfig, outputFormat = 'shell' } = await req.json();

    if (!agentConfig) {
      throw new Error('Agent configuration is required');
    }

    const { name, persona, tools, mcpServers, claudeMd } = agentConfig;

    // Generate CLAUDE.md content
    const claudeMdContent = claudeMd || `# ${name || 'My Agent'}

## IDENTITY
${persona || 'You are a helpful AI assistant.'}

## WORKFLOW
1. Understand the task requirements
2. Plan the approach
3. Execute step by step
4. Verify the results

## TOOLS
${(tools || ['Read', 'Write', 'Bash']).map((t: string) => `- ${t}`).join('\n')}

## RULES
- Follow best practices
- Write clean, maintainable code
- Test your changes
- Document your work
`;

    // Generate shell script for Linux/macOS
    const shellScript = `#!/bin/bash
# Claude Code Setup Script
# Generated by Agent Builder Platform
# Created: ${new Date().toISOString()}

set -e

echo "Setting up Claude Code environment..."

# Create project directory
PROJECT_DIR="\${HOME}/claude-projects/${(name || 'my-agent').toLowerCase().replace(/\s+/g, '-')}"
mkdir -p "\$PROJECT_DIR"
cd "\$PROJECT_DIR"

# Create CLAUDE.md
cat > CLAUDE.md << 'CLAUDEMD'
${claudeMdContent}
CLAUDEMD

echo "Created CLAUDE.md"

# Install Claude Code CLI if not present
if ! command -v claude &> /dev/null; then
    echo "Installing Claude Code CLI..."
    npm install -g @anthropic-ai/claude-code
fi

# Configure MCP servers if specified
${(mcpServers || []).length > 0 ? `
# MCP Server Configuration
cat > .mcp-servers.json << 'MCPCONFIG'
{
  "mcpServers": {
${(mcpServers || []).map((s: { id: string; config: Record<string, unknown> }) => `    "${s.id}": ${JSON.stringify(s.config || {}, null, 4)}`).join(',\n')}
  }
}
MCPCONFIG
echo "Configured MCP servers"
` : '# No MCP servers configured'}

# Create .clauderc configuration
cat > .clauderc << 'CLAUDERC'
{
  "allowedTools": ${JSON.stringify(tools || ['Read', 'Write', 'Bash'])},
  "projectName": "${name || 'My Agent'}",
  "autoApprove": false
}
CLAUDERC

echo "Created .clauderc configuration"

# Initialize git repository
git init
git add .
git commit -m "Initial Claude Code setup"

echo ""
echo "Setup complete!"
echo "Project directory: \$PROJECT_DIR"
echo ""
echo "To start Claude Code, run:"
echo "  cd \$PROJECT_DIR && claude"
`;

    // Generate PowerShell script for Windows
    const powershellScript = `# Claude Code Setup Script (Windows)
# Generated by Agent Builder Platform
# Created: ${new Date().toISOString()}

$ErrorActionPreference = "Stop"

Write-Host "Setting up Claude Code environment..."

# Create project directory
$ProjectDir = "$env:USERPROFILE\\claude-projects\\${(name || 'my-agent').toLowerCase().replace(/\s+/g, '-')}"
New-Item -ItemType Directory -Force -Path $ProjectDir | Out-Null
Set-Location $ProjectDir

# Create CLAUDE.md
@"
${claudeMdContent}
"@ | Out-File -FilePath "CLAUDE.md" -Encoding UTF8

Write-Host "Created CLAUDE.md"

# Install Claude Code CLI if not present
if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Host "Installing Claude Code CLI..."
    npm install -g @anthropic-ai/claude-code
}

# Create .clauderc configuration
@"
{
  "allowedTools": ${JSON.stringify(tools || ['Read', 'Write', 'Bash'])},
  "projectName": "${name || 'My Agent'}",
  "autoApprove": false
}
"@ | Out-File -FilePath ".clauderc" -Encoding UTF8

Write-Host "Created .clauderc configuration"

# Initialize git repository
git init
git add .
git commit -m "Initial Claude Code setup"

Write-Host ""
Write-Host "Setup complete!"
Write-Host "Project directory: $ProjectDir"
Write-Host ""
Write-Host "To start Claude Code, run:"
Write-Host "  cd $ProjectDir; claude"
`;

    const scripts = {
      shell: { content: shellScript, filename: 'setup-claude.sh', language: 'bash' },
      powershell: { content: powershellScript, filename: 'setup-claude.ps1', language: 'powershell' },
      claudemd: { content: claudeMdContent, filename: 'CLAUDE.md', language: 'markdown' }
    };

    const selectedScript = scripts[outputFormat as keyof typeof scripts] || scripts.shell;

    return new Response(JSON.stringify({
      success: true,
      data: {
        script: selectedScript.content,
        filename: selectedScript.filename,
        language: selectedScript.language,
        agentName: name || 'My Agent',
        generatedAt: new Date().toISOString()
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    return new Response(JSON.stringify({
      success: false,
      error: { code: 'SCRIPT_ERROR', message: error.message }
    }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
