# Google App Engine configuration (alternative to Cloud Run)
# Use: gcloud app deploy

runtime: nodejs20
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
  REGION: 'australia-southeast1'

handlers:
  - url: /.*
    script: auto
    secure: always

network:
  session_affinity: true
